server:
  port: 3455

spring:
  application:
    name: metadata
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database: postgresql
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error

